"""Initial migration.

Revision ID: d79a6ad36450
Revises: 
Create Date: 2022-04-29 10:28:35.983149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79a6ad36450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('homeworld', sa.String(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('skin_color', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('starships', sa.String(), nullable=True),
    sa.Column('vehicles', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_model')
    # ### end Alembic commands ###
